print("hello world")
print("hello hello!")
print("Goodbye world")
print("Hello! Goodbye!")
print("this is a test, 123")
print("alpha, bravo, charlie, delta")
print("echo, foxtrot")
print("Yay Pyladies")
